import Image from "next/image";
import Link from "next/link";
import { ArrowDown, MapPin, Users, Utensils } from "lucide-react";
import { Button } from "@/components/Button";
import { Section } from "@/components/Section";
import { SpotCard } from "@/components/SpotCard";
import { Stagger, StaggerItem } from "@/components/motion/Stagger";
import { Reveal } from "@/components/motion/Reveal";
import { Parallax } from "@/components/motion/Parallax";
import { CTA } from "@/components/CTA";
import { FAQ } from "@/components/FAQ";
import { areas, spots } from "@/lib/content";

export default function Home(){ const featured=spots.slice(0,3); const food=spots.filter(s=>s.type==='Food Stall'); return <>
<section className="relative overflow-hidden pt-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-8 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-16"><div className="relative z-10 order-2 lg:order-1"><Reveal><p className="eyebrow text-terracotta">HYDERABAD · COMMUNITY GUIDE</p></Reveal><Reveal delay={.08}><h1 className="mt-4 max-w-xl font-heading text-balance text-5xl leading-[.98] text-maroon sm:text-6xl lg:text-7xl">Hyderabad, recommended by the people who've actually been there.</h1></Reveal><Reveal delay={.16}><p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">Must-visit places and must-try food stalls — with real addresses — added by travellers and locals, not advertisers.</p></Reveal><Reveal delay={.24}><div className="mt-8 flex flex-wrap gap-3"><Button href="#guide">Explore Hyderabad Guide</Button><Button href="/add" variant="secondary">Add your own spot</Button><a href="https://wa.me/1234567890?text=Hi%20travelguide%2C%20I%20found%20you%20on%20your%20website%20and%20would%20like%20to%20know%20more." className="inline-flex min-h-11 items-center justify-center rounded-full px-4 text-sm font-semibold text-maroon underline-link">WhatsApp us</a></div></Reveal></div><div className="order-1 lg:order-2"><Reveal><Parallax><div className="relative overflow-hidden rounded-[28px] hero-shadow"><Image src="/images/hero-hyderabad-collage.webp" alt="Warm documentary-style view of Hyderabad with Charminar and a traveller checking a map" width={1280} height={720} priority className="h-auto w-full scale-[1.02] object-cover"/><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-maroon/20 to-transparent"/></div></Parallax></Reveal></div></div><div className="mx-auto max-w-7xl px-5 pb-8 sm:px-8 lg:px-10"><a href="#guide" className="inline-flex items-center gap-2 text-sm font-semibold text-maroon/65"><ArrowDown size={16}/>Scroll to explore</a></div></section>

<section className="border-y border-maroon/10 bg-white/55"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-9 sm:grid-cols-3 sm:px-8 lg:px-10"><div><p className="font-heading text-xl text-maroon">Added by travellers</p><p className="mt-1 text-sm text-ink/60">The community adds the finds; the guide gives them a home.</p></div><div><p className="font-heading text-xl text-maroon">Hyderabad first</p><p className="mt-1 text-sm text-ink/60">Depth in one city instead of a thin list of everywhere.</p></div><div><p className="font-heading text-xl text-maroon">Free to explore</p><p className="mt-1 text-sm text-ink/60">No pay-to-be-seen listings in the stated model.</p></div></div></section>

<Section id="guide" eyebrow="Featured finds" title="Start with the places people come to Hyderabad for." intro="A calm shortlist for the first look. Detailed contributor names, dates and addresses are marked for confirmation where the source data does not yet provide them."><div className="mt-10 grid gap-5 md:grid-cols-3">{featured.map((s,i)=><SpotCard key={s.slug} spot={s} index={i}/>)}</div><div className="mt-8"><Button href="/explore" variant="secondary">Browse the full guide</Button></div></Section>

<section className="bg-white/50"><Section eyebrow="Street food" title="Food worth stopping for." intro="From Irani chai to a steaming handi of biryani, the food side of the guide is built around useful details, not glossy listicles."><div className="mt-10 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Reveal><div className="relative min-h-[340px] overflow-hidden rounded-3xl"><Image src="/images/food-street-stall-wide.webp" alt="Busy but calm Hyderabad street food stall at dusk" fill sizes="(max-width: 1024px) 90vw, 55vw" className="object-cover"/></div></Reveal><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1">{food.map((s,i)=><SpotCard key={s.slug} spot={s} index={i}/>)}</div></div></Section></section>

<Section eyebrow="Browse by area" title="Choose the part of Hyderabad you are in." intro="Area-first browsing keeps a travel day practical: find what is close before you start chasing the next stop."><Stagger className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{areas.map(a=><StaggerItem key={a.slug}><Link href={`/explore?area=${a.slug}`} className="group block overflow-hidden rounded-3xl border border-maroon/10 bg-white"><div className="relative aspect-square overflow-hidden"><Image src={a.image} alt={`${a.name} in Hyderabad`} fill sizes="(max-width: 768px) 45vw, 20vw" className="object-cover transition duration-700 group-hover:scale-[1.04]"/></div><div className="p-5"><h3 className="font-heading text-xl text-maroon">{a.name}</h3><p className="mt-2 text-sm leading-5 text-ink/65">{a.description}</p></div></Link></StaggerItem>)}</Stagger></Section>

<section className="bg-maroon text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-28"><Reveal><p className="eyebrow text-turmeric">How it works</p><h2 className="mt-3 font-heading text-4xl leading-tight sm:text-5xl">A guide that gets better when people share what they know.</h2><p className="mt-5 max-w-md leading-7 text-white/70">The community is the source. travelguide is the place where those useful finds can be discovered, credited and kept together.</p></Reveal><Stagger className="grid gap-4 sm:grid-cols-3">{[['01','Explore','Travellers find places and food worth remembering.'],['02','Add','Travellers add a new find with practical details.'],['03','Grow','The guide becomes more useful for everyone.']].map(([n,t,d])=><StaggerItem key={n}><div className="rounded-3xl border border-white/10 bg-white/5 p-5"><span className="font-heading text-3xl text-turmeric">{n}</span><h3 className="mt-8 font-heading text-2xl">{t}</h3><p className="mt-2 text-sm leading-6 text-white/65">{d}</p></div></StaggerItem>)}</Stagger></div></section>

<Section eyebrow="Recently added" title="Keep an eye on what the community is finding." intro="The live submission feed will populate as people add places and food stalls. Starter entries below intentionally show the information still awaiting contributor confirmation."><div className="mt-10 grid gap-3">{spots.slice(0,5).map((s,i)=><Reveal key={s.slug} delay={i*.05}><Link href={`/spot/${s.slug}`} className="group flex flex-col gap-4 rounded-2xl border border-maroon/10 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-sand text-terracotta">{s.type==='Place'?<MapPin size={20}/>:<Utensils size={20}/>}</div><div><p className="font-heading text-xl text-maroon">{s.name}</p><p className="mt-1 text-sm text-ink/60">{s.area} · Added {s.added}</p></div></div><span className="text-sm font-semibold text-terracotta">View spot →</span></Link></Reveal>)}</div></Section>

<CTA/>
<section className="border-t border-maroon/10"><Section eyebrow="Questions" title="Before you head out, know how the guide works."><FAQ/></Section></section>

<div className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-10"><div className="rounded-3xl border border-maroon/10 bg-white p-7 sm:p-10"><div className="flex flex-wrap items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-turmeric/20 text-maroon"><Users size={20}/></span><div><p className="font-heading text-2xl text-maroon">Built for travellers, not advertisers.</p><p className="mt-1 text-sm text-ink/60">Every recommendation is intended to be community-sourced. [Confirm moderation process before launch.]</p></div><Link href="/about" className="ml-auto underline-link text-sm font-semibold text-maroon">Read our model</Link></div></div></div>
</>; }